#!/bin/bash
#
#
echo "Sisestage palun kõik kolmnurga küljed:"
read a b c 
# see arvutab kolmnurga pool ümbermõõtu
p=`expr $a \+ $b \+ $c`
p1=`expr $p \/ 2`
x=`expr $p1 \- $a`
y=`expr $p1 \- $b`
z=`expr $p1 \- $c`
t=`expr $x \* $y \* $z`
f=`expr $p1 \* $t`
s=$(echo "$f" | awk '{print sqrt($1)}')
echo "kolmnurga pindala on: $s ja ümbermõõt on: $p"
#
#skripti lõpp

